CREATE COLUMN TABLE "TWEETS"."TWEETS" (
 "ID" BIGINT CS_FIXED,
 "CREATEDAT" LONGDATE CS_LONGDATE, 
 "LATITUDE" DECIMAL CS_DECIMAL_FLOAT, 
 "LONGITUDE" DECIMAL CS_DECIMAL_FLOAT, 
 "USERNAME" NVARCHAR(100), "CONTENT" NVARCHAR(500), 
 "RETWEET" NVARCHAR(1), 
 "RTID" BIGINT CS_FIXED, 
 "RTUSERNAME" NVARCHAR(100), 
 "LOCATION" NVARCHAR(100), 
 "FOLLOWERS" INTEGER CS_INT, 
 "RTFOLLOWERS" INTEGER CS_INT, 
 PRIMARY KEY ("ID")
);
